### ISSUE TITLE
With gradio 6  JS does NOT work after move from init to launch, so must downgrade to gradio 5.49.1

### ISSUE THREAD

**Issue by AngelTs** [gradio-app/gradio#12486]
### Describe the bug

gradio 6 does not work with theme keyword, use gradio 5.49.1

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

...
with gr.Blocks(title=".....", theme=gr.themes.Soft(), 
...
will produce the error:
[TypeError: BlockContext.__init__() got an unexpected keyword argument 'theme'

```


### Screenshot

_No response_

### Logs

```shell

```

### System Info

```shell
gradio 6
gradio 5.49.1
```

### Severity

I can work around it

**Comment by AngelTs** [comment]
MOREOVER:
You can't use head, css or js in with gr.Blocks(title=".....", ...), only in demo.launch(...), BUT in this case JS DOES NOT WORK!!!
downgrade to gradio 5.49.1 is the only option for now!!!
(also can't use show_download_button and show_api?!?)

**Comment by freddyaboulton** [comment]
Hi @AngelTs - can you please share an app where `js` in launch does not work?

**Comment by freddyaboulton** [comment]
> (also can't use show_download_button and show_api?!?)

This is covered in the migration guide: https://www.gradio.app/main/guides/gradio-6-migration-guide#show-api-parameter-replaced-with-footer-links

**Comment by freddyaboulton** [comment]
Hi @AngelTs - can you please share a minimal reproducer?

**Comment by AngelTs** [comment]
> Hi [@AngelTs](https://github.com/AngelTs) - can you please share a minimal reproducer?

1.
In gradio 5.49.1 and gradio_client 1.13.3 next code work:
```
with gr.Blocks(title="sample", theme=gr.themes.Default(), 
            js="""
                        function() {
                                    document.addEventListener('click', e => {
                                    console.log("clicked event");
                                    alert("clicked event");
                                    }, true);
                        }
            """
) as demo:

```

2.
In gradio 6.0.2 and gradio_client 2.0.1 next code DOES NOT work:
```
with gr.Blocks(title="sample") as demo:
js1="""

            function() {
                        document.addEventListener('click', e => {
                        console.log("clicked event");
                        alert("clicked event");
                        }, true);
            }
"""
demo.launch(

            theme=gr.themes.Default(),
            js=js1
)`
```

**Comment by freddyaboulton** [comment]
Thank you, we'll take a look

**Comment by dawoodkhan82** [comment]
@AngelTs Have a PR to fix this here: https://github.com/gradio-app/gradio/pull/12508

Thanks for flagging!

**Comment by AngelTs** [comment]
> [@AngelTs](https://github.com/AngelTs) Have a PR to fix this here: [#12508](https://github.com/gradio-app/gradio/pull/12508)
> 
> Thanks for flagging!

This particular js code continue to NOT works in gradio 6.1.0

Uncaught SyntaxError: Failed to execute 'appendChild' on 'Node': Function statements require a function name
at Index-Czfua_SX.js:2:14729

in Index-Czfua_SX.js:2:14729:
document.head.appendChild(_)

**Comment by freddyaboulton** [comment]
Hi @AngelTs ! Please give your function a name and then call it. This should work:

```python
import gradio as gr

js1="""
    function click() {
                document.addEventListener('click', e => {
                console.log("clicked event");
                alert("clicked event");
                }, true);
    }
    click();
"""

with gr.Blocks(title="sample") as demo:
    pass

demo.launch(
        theme=gr.themes.Default(),
        js=js1
)
```

More details about this (with possible workarounds) here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unnamed_function_statement

**Comment by AngelTs** [comment]
> Hi [@AngelTs](https://github.com/AngelTs) ! Please give your function a name and then call it. This should work:
> 
> import gradio as gr
> 
> js1="""
>     function click() {
>                 document.addEventListener('click', e => {
>                 console.log("clicked event");
>                 alert("clicked event");
>                 }, true);
>     }
>     click();
> """
> 
> with gr.Blocks(title="sample") as demo:
>     pass
> 
> demo.launch(
>         theme=gr.themes.Default(),
>         js=js1
> )
> More details about this (with possible workarounds) here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unnamed_function_statement

Thank you, this helps alittle, but something MAJOR is wrong and absolutly working JS code in gradio 5 in 6 does not work any more - it must be totaly rewritten, not only replaced!. So it is important to put this notice in migration docs, because something brokes JS on a basic level. I have very complex JS code and there is no way to make it work in gradio 6.

**Comment by AngelTs** [comment]
Finally i found what brokes the js code in launch (in gradio 6) but works in init/blocks (in gradio 5):
If use mix of """ + python code (to comment js code in python file, but not to show in browser)
replace
`
js="""
...js code...
"""
...python code...
+"""...js code...
"""
`
with 
`
js="""
...js code...
"""
...python code... 
js +="""
...js code...
"""
`
