### ISSUE TITLE
About the running bug of matplotlib in demo/outbreak_forecast/run.py

### ISSUE THREAD

**Issue by Zengyf-CVer** [gradio-app/gradio#1011]
### Describe the bug

I ran the file `https://github.com/gradio-app/gradio/blob/main/demo/outbreak_forecast/run.py`, the default Plot Type is `matplotlib`, clicked submit, and an error occurred :

```shell
pandas.errors.InvalidIndexError: (slice(None, None, None), None)
```

### Reproduction

https://github.com/gradio-app/gradio/blob/main/demo/outbreak_forecast/run.py

my configuration:
```shell
gradio                       2.9.4
matplotlib                   3.5.1
plotly                       5.7.0
bokeh                        2.4.2
```
![ksnip_20220417-175306](https://user-images.githubusercontent.com/41098760/163709440-4879712e-d8db-4f99-af50-2b2b5b5e7065.png)

Error message:

```shell
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 142, in pandas._libs.index.IndexEngine.get_loc
TypeError: '(slice(None, None, None), None)' is an invalid key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/gradio/routes.py", line 269, in predict
    output = await run_in_threadpool(app.launchable.process_api, body, username)
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/gradio/interface.py", line 573, in process_api
    prediction, durations = self.process(raw_input)
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/gradio/interface.py", line 615, in process
    predictions, durations = self.run_prediction(
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/gradio/interface.py", line 531, in run_prediction
    prediction = predict_fn(*processed_input)
  File "test49.py", line 32, in outbreak
    plt.plot(df['day'], df[countries])
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2757, in plot
    return gca().plot(
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 1632, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 312, in __call__
    yield from self._plot_args(this, kwargs)
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 488, in _plot_args
    y = _check_1d(xy[1])
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 1327, in _check_1d
    ndim = x[:, None].ndim
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3628, in get_loc
    self._check_indexing_error(key)
  File "/home/zyf/anaconda3/envs/yolo/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5637, in _check_indexing_error
    raise InvalidIndexError(key)
pandas.errors.InvalidIndexError: (slice(None, None, None), None)
```

### System Info

```shell
my configuration:

gradio                       2.9.4
matplotlib                   3.5.1
plotly                       5.7.0
bokeh                        2.4.2


Ubuntu 20.04
Chrome
```

### Severity

annoyance

**Comment by abidlabs** [comment]
Thanks @Zengyf-CVer for creating this issue! We'll look into it shortly

**Comment by abidlabs** [comment]
@dawoodkhan82 I tested this on the latest version of gradio, and while this error doesn't appear, it looks like `matplotlib` plots are broken. When I clicked submit, nothing would show up if matplotlib was selected:

![image](https://user-images.githubusercontent.com/1778297/164066466-7be3e883-5b36-4668-ae30-d32f5f707b02.png)

The other two plot types (bokeh and plotly) would work just fine.

**Comment by dawoodkhan82** [comment]
> @dawoodkhan82 I tested this on the latest version of gradio, and while this error doesn't appear, it looks like `matplotlib` plots are broken. When I clicked submit, nothing would show up if matplotlib was selected:
> 
> ![image](https://user-images.githubusercontent.com/1778297/164066466-7be3e883-5b36-4668-ae30-d32f5f707b02.png)
> 
> The other two plot types (bokeh and plotly) would work just fine.

This turned out to be an issue with the demo. Fixed in this pr (https://github.com/gradio-app/gradio/pull/1044)

**Comment by Zengyf-CVer** [comment]
@abidlabs 
I rerun this file:
https://github.com/gradio-app/gradio/blob/main/demo/outbreak_forecast/run.py

Error message:
```shell
Traceback (most recent call last):
  File "test.py", line 60, in <module>
    outputs = gr.Plot()
TypeError: __init__() missing 1 required positional argument: 'value'
```

- gradio 3.0.3
- ubuntu 20.04
- chrome

**Comment by Zengyf-CVer** [comment]
@abidlabs  @dawoodkhan82 
https://gradio.app/docs/#plot
![ksnip_20220522-174633](https://user-images.githubusercontent.com/41098760/169689428-c356c47e-0271-44bf-9978-867505a26d64.png)

The code for this column `outbreak_foracast` works fine in gradio 3.0.2, but fails in `3.0.3`:

```shell
Traceback (most recent call last):
  File "test.py", line 63, in <module>
    outputs = gr.Plot()
TypeError: __init__() missing 1 required positional argument: 'value'
```

**Comment by abidlabs** [comment]
Sorry I issued a hotfix. Should work again in `3.0.4`
