### ISSUE TITLE
Request object has no `__json_response_data`

### ISSUE THREAD

**Issue by keturn** [gradio-app/gradio#2290]
### Describe the bug

When attempting to return results through a generator, there's an error from gradio internals.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://github.com/keturn/sd-progress-demo/blob/f415d3bdb5dbad90db6d451558a23edee3660841/progress_callback_demo.ipynb

### Logs

```
Task exception was never retrieved
future: <Task finished name='Task-71' coro=<Queue.process_event() done, defined at 🐍/lib/python3.10/site-packages/gradio/queue.py:222> exception=AttributeError("'Request' object has no attribute '_json_response_data'")>
Traceback (most recent call last):
  File "🐍/lib/python3.10/site-packages/gradio/queue.py", line 231, in process_event
    if response.json.get("is_generating", False):
  File "🐍/lib/python3.10/site-packages/gradio/utils.py", line 592, in json
    return self._json_response_data
AttributeError: 'Request' object has no attribute '_json_response_data'
```

### System Info

```shell
gradio 3.3.1
ubuntu 22.04
python 3.10.4
Firefox 104.0.2
```

### Severity

blocking all usage of gradio (not "all" maybe, but "has workaround" was not appropriate)

**Comment by SkyTNT** [comment]
same as #2261

**Comment by keturn** [comment]
I read #2261 as saying that if an exception such as this AttributeError happens at a particular point, it is handled poorly. Which is important to fix, I agree.

but presumably the thing triggering this particular AttributeError should be fixed as well.

**Comment by freddyaboulton** [comment]
I think #2261 prevents the `has no attribute '_json_response_data'` by checking if the request has an exception. Hopefully this should be fixed in the next release.

**Comment by freddyaboulton** [comment]
@keturn Have you run into the same `_json_response_data` attribute error after upgrading to 3.4?

**Comment by abidlabs** [comment]
I think we can close this issue if users haven't reported the same attribute error in `3.4`.
