### PR TITLE
Fix fullscreen button not working in ImageSlider, interactive Image, native plots, and AnnotatedImage

### LINKED ISSUE #13442: Fullscreen button not working in ImageSlider (Gradio 6.15.2)
### Describe the bug

📄 Description
In Gradio 6.15.2, the fullscreen button rendered inside ImageSlider triggers a JavaScript runtime error when clicked.
The button is visible and interactive, but the callback is not properly defined, resulting a bug.
🔁 Steps to reproduce
```
import gradio as gr
from PIL import Image

img = Image.new("RGB", (512, 512), "red")

with gr.Blocks() as demo:
    gr.ImageSlider(value=(img, img), label="Test")

demo.launch()
```
1. Open the app in browser
2. Click the fullscreen button on the ImageSlider component

Console error:
Uncaught TypeError: e.onclick is not a function
    at HTMLButtonElement.onclick (FullscreenButton-*.js)

Fullscreen does not activate.

✅ Expected behavior
Clicking the fullscreen button should toggle fullscreen mode for ImageSlider without errors.

🔍 Root cause analysis
From compiled frontend code:

onclick: () => e.onclick(true)
and
onclick: () => e.onclick(false)

However, e.onclick is not defined or not passed correctly from ImageSlider to FullscreenButton, resulting in:
e.onclick === undefined
which leads to:
TypeError: e.onclick is not a function

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
from PIL import Image

img = Image.new("RGB", (512, 512), "red")

with gr.Blocks() as demo:
    gr.ImageSlider(value=(img, img), label="Test")

demo.launch()
```

### Screenshot

_No response_

### Logs

```shell
index-iG-u5S-q.js:45 Uncaught TypeError: e.onclick is not a function
    at HTMLButtonElement.onclick (FullscreenButton-BAuJSnhH.js:1:813)
    at i.__click (ScrollFade.svelte_svelte_type_style_lang-DsKPVR6v.js:1:934)
    at HTMLElement.dt (index-iG-u5S-q.js:45:27220)
```

### System Info

```shell
pip list | findstr gradio
gradio                                      6.15.2
gradio_client                               2.5.0
hf-gradio                                   0.4.1
```

### Severity

I can work around it

### PR DESCRIPTION
**Pull request by hysts**
## Description

The fullscreen button does nothing when clicked in four components: `gr.ImageSlider`, interactive `gr.Image`, native plots (`gr.LinePlot`, `gr.ScatterPlot`, `gr.BarPlot`), and `gr.AnnotatedImage`. The browser console shows `Uncaught TypeError: e.onclick is not a function`.

The shared `FullscreenButton` atom changed its API in the Svelte 5 migration (#12779): it used to dispatch a `fullscreen` event, and now requires an `onclick: (fullscreen: boolean) => void` prop. Four call sites were never updated and still used the old `on:fullscreen` wiring, so `onclick` was undefined and clicking threw. The static `gr.Image` and Gallery instances of this bug were fixed earlier in #13004 and #12865; this PR updates the remaining call sites the same way:

- `js/imageslider/shared/SliderPreview.svelte` and `js/image/shared/ImageUploader.svelte`: wire `onclick` to update the local `fullscreen` state and dispatch a component-level `fullscreen` event, which their parent `Index.svelte` files already listen for (same pattern as the ImagePreview fix in #13004).
- `js/nativeplot/Index.svelte` and `js/annotatedimage/Index.svelte`: replace the inline `on:fullscreen` handler with an `onclick` handler (same pattern as `js/plot/Index.svelte`).

In nativeplot, the now-working fullscreen toggle re-renders the chart and exposed a small race in `load_chart`: the function can resume from `await import("vega-embed")` after the component has unmounted, calling `vegaEmbed` with a null element and producing an unhandled promise rejection. Added a null check after the await.

Each component gets a unit test that clicks the fullscreen button and asserts the mode toggles on and off. All four tests fail on `main` with the `onclick is not a function` error and pass with this fix.

Note: the 2026 comments on #10268 reporting that the fullscreen button "does nothing" on `gr.Image` are the interactive-Image instance of this bug and are fixed here as well (the coordinate issue that #10268 is actually about is being addressed separately).

Closes: #13442

## AI Disclosure

- [x] I used AI to investigate the root cause and implement the fix.
- [ ] I did not use AI

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Testing and Formatting Your Code

1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the backed tests: `bash scripts/run_backend_tests.sh`

2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any changes to non-Python files) `bash scripts/format_frontend.sh`

### CODE REVIEW

**Review by hannahblair — APPROVED** [review]
Image

tested and looks good! thanks @hysts :)

**Comment by hysts** [comment]
Thanks for the review @hannahblair ! Merging.
