### ISSUE TITLE
Mypy cannot find component event methods before the first Gradio import

### ISSUE THREAD

**Issue by manocormen** [gradio-app/gradio#13781]
### Describe the bug

After upgrading from Gradio 6.14.0 to 6.25.0, our CI caught a mypy error for component event methods such as `Button.click()`. In a clean environment, the check fails initially and succeeds after running `python -c "import gradio"` once.

The 6.14.0 wheel contains `gradio/components/button.pyi`, while 6.25.0 does not. [Gradio's build configuration](https://github.com/gradio-app/gradio/blob/375335e60e2b4504a57f3eef0eb6bca3c7bb765a/pyproject.toml#L73-L79) still lists `*.pyi` and `py.typed` as artifacts. Could the component stubs have been inadvertently omitted during packaging?

I would expect static type checking to work immediately after installation, without requiring this initial import.

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

Create `repro.py`:

```python
import gradio as gr

button = gr.Button()
button.click(lambda: None)
```

Then, in a fresh Python environment:

```shell
pip install gradio==6.25.0 mypy==2.1.0
python -m mypy repro.py
python -c "import gradio"
python -m mypy repro.py
```

The first mypy invocation fails. After importing Gradio once, the same invocation succeeds.

### Logs

```shell
$ python -m mypy repro.py
repro.py:4: error: "Button" has no attribute "click"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)

$ python -c "import gradio"

$ python -m mypy repro.py
Success: no issues found in 1 source file
```

### System Info

```shell
Operating System: Linux
Gradio: 6.25.0
gradio_client: 2.6.0
Python: 3.14.4
mypy: 2.1.0
```

### Severity

I can work around it

**Comment by Darkslayer3324j** [comment]
The stubs aren't being dropped by the `artifacts` glob — they don't exist when the wheel is built.

**Mechanism.** `gradio/components/*.pyi` are generated as a side effect of importing gradio: `ComponentMeta.__new__` calls `create_or_modify_pyi()` at class-definition time (`gradio/component_meta.py`). `.gitignore` ignores `*.pyi` with a single exception for `gradio/stubs/**/*.pyi`, so they are never committed. A clean checkout therefore has zero component stubs, and `python -m build` / `uv build` runs the backend in an isolated environment where gradio is never imported — so nothing generates them before file collection.

**Reproduction** on a clean checkout of `main` (`44f8712`):

```console
$ ls gradio/components/*.pyi | wc -l
0
$ uv build --wheel
Successfully built dist/gradio-6.26.0-py3-none-any.whl
$ python -c "import zipfile; z = zipfile.ZipFile('dist/gradio-6.26.0-py3-none-any.whl'); \
print([x for x in z.namelist() if x.endswith('.pyi')])"
['gradio/stubs/anyio.pyi']
```

One stub — the un-ignored one. No `gradio/components/button.pyi`. `py.typed` **is** present, which is what makes the failure mode confusing: mypy trusts the package as typed, then finds no `click` on `Button`.

**The `artifacts` config is fine.** Same tree, same `pyproject.toml`; the only variable is whether the file exists at build time:

| build | `.pyi` in wheel |
| --- | --- |
| clean checkout | 1 (`gradio/stubs/anyio.pyi`) |
| after creating `gradio/components/button.pyi` | 2 (`components/button.pyi` included) |

So `artifacts = ["*.pyi"]` picks the stubs up correctly whenever they are on disk.

**Why 6.14.0 had them and 6.25.0 doesn't.** Nothing in the packaging path guarantees generation, so whether stubs ship depends on whether the build tree happened to have gradio imported already. That makes wheel contents environment-dependent rather than reproducible, which fits a regression appearing with no related change.

Worth noting `.github/workflows/test-python.yml` has a `Generate .pyi files` step that runs `python -c "import gradio"` — but it runs *after* `uv pip install dist/*.whl`, so it repairs the installed copy for the test run rather than populating the tree before `python -m build`. CI is consequently green on a wheel that is missing the stubs.

**Fix options**, in the order I'd rank them:

1. **Commit the component stubs** (drop `*.pyi` from `.gitignore` for `gradio/components/`, as already done for `gradio/stubs/**`), with a CI check that `python -c "import gradio"` leaves the tree clean. Deterministic, covers sdist and every third-party build path, adds no build-time dependency. Cost is ~40 generated files tracked in git.
2. **A hatchling build hook** that generates stubs in `initialize()`. Cleaner conceptually, but generation requires importing gradio, so its runtime dependencies would have to move into `build-system.requires` — a heavy build.
3. **Generate before building in the release pipeline.** Smallest diff, but the publish step is `gradio-app/github/actions/publish-pypi@main` in another repo, so it isn't fixable from here and does nothing for anyone building from the sdist.

Happy to open a PR for (1), including the CI drift check, if that's the direction you'd want.

<sub>Investigated with AI assistance. Every command above was run locally against `44f8712`; the output is verbatim and reproducible from a clean checkout.</sub>

**Comment by Darkslayer3324j** [comment]
Thanks for picking this up so quickly @abidlabs, and for tracking it back to #13576 — that was the piece I couldn't see from outside. It makes sense now: docs generation was importing Gradio as a side effect, that import generated the stubs, and `skip_docs_gen: true` removed the only thing keeping them in the wheel.

Generating them explicitly in the test, preview and publish workflows looks like the right call over committing ~40 generated files.

Nothing needed from me — just glad it's sorted.
