### ISSUE TITLE
Fullscreen button not working in ImageSlider (Gradio 6.15.2)

### ISSUE THREAD

**Issue by SModelo059** [gradio-app/gradio#13442]
### Describe the bug

📄 Description
In Gradio 6.15.2, the fullscreen button rendered inside ImageSlider triggers a JavaScript runtime error when clicked.
The button is visible and interactive, but the callback is not properly defined, resulting a bug.
🔁 Steps to reproduce
```
import gradio as gr
from PIL import Image

img = Image.new("RGB", (512, 512), "red")

with gr.Blocks() as demo:
    gr.ImageSlider(value=(img, img), label="Test")

demo.launch()
```
1. Open the app in browser
2. Click the fullscreen button on the ImageSlider component

Console error:
Uncaught TypeError: e.onclick is not a function
    at HTMLButtonElement.onclick (FullscreenButton-*.js)

Fullscreen does not activate.

✅ Expected behavior
Clicking the fullscreen button should toggle fullscreen mode for ImageSlider without errors.

🔍 Root cause analysis
From compiled frontend code:

onclick: () => e.onclick(true)
and
onclick: () => e.onclick(false)

However, e.onclick is not defined or not passed correctly from ImageSlider to FullscreenButton, resulting in:
e.onclick === undefined
which leads to:
TypeError: e.onclick is not a function

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
from PIL import Image

img = Image.new("RGB", (512, 512), "red")

with gr.Blocks() as demo:
    gr.ImageSlider(value=(img, img), label="Test")

demo.launch()
```

### Logs

```shell
index-iG-u5S-q.js:45 Uncaught TypeError: e.onclick is not a function
    at HTMLButtonElement.onclick (FullscreenButton-BAuJSnhH.js:1:813)
    at i.__click (ScrollFade.svelte_svelte_type_style_lang-DsKPVR6v.js:1:934)
    at HTMLElement.dt (index-iG-u5S-q.js:45:27220)
```

### System Info

```shell
pip list | findstr gradio
gradio                                      6.15.2
gradio_client                               2.5.0
hf-gradio                                   0.4.1
```

### Severity

I can work around it

**Comment by Aniket-16-S** [comment]
Can i work on this ?
Assign to me if open.
