### PR TITLE
Fix component stubs missing from clean Gradio wheels

### LINKED ISSUE #13781: Mypy cannot find component event methods before the first Gradio import
### Describe the bug

After upgrading from Gradio 6.14.0 to 6.25.0, our CI caught a mypy error for component event methods such as `Button.click()`. In a clean environment, the check fails initially and succeeds after running `python -c "import gradio"` once.

The 6.14.0 wheel contains `gradio/components/button.pyi`, while 6.25.0 does not. [Gradio's build configuration](https://github.com/gradio-app/gradio/blob/375335e60e2b4504a57f3eef0eb6bca3c7bb765a/pyproject.toml#L73-L79) still lists `*.pyi` and `py.typed` as artifacts. Could the component stubs have been inadvertently omitted during packaging?

I would expect static type checking to work immediately after installation, without requiring this initial import.

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

Create `repro.py`:

```python
import gradio as gr

button = gr.Button()
button.click(lambda: None)
```

Then, in a fresh Python environment:

```shell
pip install gradio==6.25.0 mypy==2.1.0
python -m mypy repro.py
python -c "import gradio"
python -m mypy repro.py
```

The first mypy invocation fails. After importing Gradio once, the same invocation succeeds.

### Screenshot

_No response_

### Logs

```shell
$ python -m mypy repro.py
repro.py:4: error: "Button" has no attribute "click"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)

$ python -c "import gradio"

$ python -m mypy repro.py
Success: no issues found in 1 source file
```

### System Info

```shell
Operating System: Linux
Gradio: 6.25.0
gradio_client: 2.6.0
Python: 3.14.4
mypy: 2.1.0
```

### Severity

I can work around it

### PR DESCRIPTION
**Pull request by abidlabs**
## Description

Clean Gradio package builds omit the generated component stubs, so mypy cannot see event methods such as `Button.click()` until Gradio is imported once.

This change explicitly generates the ignored component stubs immediately before Python package builds in the test, preview, and publishing workflows. The existing test-phase import remains to create local stubs for `test_event_pyi_file_matches_source_code` and is labeled accordingly.

### Root cause

The exact trigger was #13576 (`9e63dfdad`), which added `skip_docs_gen: true` to release builds. Component stubs were ignored by Git and generated only as a side effect of importing Gradio. Previously, documentation generation imported `gradio.themes`, indirectly generating the stubs before packaging:

`docs generation → import Gradio → generate stubs → wheel includes stubs`

After documentation generation was skipped, no pre-build import occurred:

`skip docs generation → no Gradio import → no stubs → wheel omits stubs`

No component API change removed `Button.click()`; the build optimization exposed a latent dependency on an incidental import. The fix makes that required generation step explicit without committing roughly 21,000 lines of generated stubs.

Closes: #13781

## Verification

- Generated the stubs with `python3 -c "import gradio"`.
- Built the wheel and source distribution with `python3 -m build`.
- Verified all 47 component stubs are present in both artifacts and that the packaged `button.pyi` contains `Button.click()`.
- Ran `python3 -m pytest test/test_events.py::test_event_pyi_file_matches_source_code -q`.
- Confirmed all three modified workflow YAML files parse successfully.

Minimal demo:

```python
import gradio as gr


with gr.Blocks() as demo:
    name = gr.Textbox(label="Name")
    button = gr.Button("Greet")
    greeting = gr.Textbox(label="Greeting")
    button.click(lambda value: f"Hello, {value}!", inputs=name, outputs=greeting)


if __name__ == "__main__":
    demo.launch()
```

The demo file is temporary and was not committed.

## AI Disclosure

- [x] I used Codex to reproduce and diagnose the issue, implement the workflow changes, run verification, and draft this PR description. I self-reviewed the resulting changes.
- [ ] I did not use AI

## 🎯 PRs Should Target Issues

This PR targets #13781.

## Testing and Formatting Your Code

This PR changes GitHub workflow YAML only. Local package-build verification is listed above; the full workflow suite is running in CI.

### CODE REVIEW

**Comment by abidlabs** [comment]
## Before / after Spaces


- [Before fix](https://huggingface.co/spaces/abidlabs/gradio-13781-before) — latest released Gradio
- [After fix](https://huggingface.co/spaces/abidlabs/gradio-13781-after) — preview wheel from this PR

| Space | Browser behavior | Packaging behavior |
| --- | --- | --- |
| Before | `Button.click()` runs and returns `Hello, Gradio!` | Released wheel omits generated component stubs, so a clean mypy run cannot see `Button.click()` before importing Gradio. |
| After | `Button.click()` runs and returns `Hello, Gradio!` | PR wheel contains all 47 component stubs, and the clean mypy reproduction passes before importing Gradio. |

This is a packaging/static-typing regression rather than a runtime UI regression, so the two browser UIs are intentionally identical. I verified that both Spaces reached `RUNNING` and exercised the button interaction in each.

**Review by hysts — APPROVED** [review]
Thanks @abidlabs ! LGTM
