### ISSUE TITLE
theme builder example doesn't work for `3.25.0` or later

### ISSUE THREAD

**Issue by deepkyu** [gradio-app/gradio#3864]
### Describe the bug

As mentioned in [Gradio Themeing Guide](https://gradio.app/theming-guide/#using-the-theme-builder) and thanks to #3664 ,
an awesome Gradio theme builder should be executed with

```python
import gradio as gr

gr.themes.builder()
```

But this raises an error in `gradio==3.25.0` or later version with the following message:
```plain
AttributeError: module 'gradio' has no attribute 'documentation'
```

I think the problem is that `gr.documentation` is moved to `gradio_client.documentation` and you mistakenly lost those ones.  

You may change the [following lines](https://github.com/gradio-app/gradio/blob/v3.24.1/gradio/themes/builder.py#L19-L22) from:

```python
docs_theme_core = gr.documentation.document_fn(gr.themes.Base.__init__, gr.themes.Base)[
    1
]
docs_theme_vars = gr.documentation.document_fn(gr.themes.Base.set, gr.themes.Base)[1]
```

to

```python
from gradio_client.documentation import document_fn

docs_theme_core = document_fn(gr.themes.Base.__init__, gr.themes.Base)[
    1
]
docs_theme_vars = document_fn(gr.themes.Base.set, gr.themes.Base)[1]
```

FYI, This also raises an error in [`theme_builder` demo in HF Spaces](https://huggingface.co/spaces/gradio/theme_builder)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

gr.themes.builder()
```

### Logs

```shell
Traceback (most recent call last):
  File "demo.py", line 15, in <module>
    gr.themes.builder()
  File "/home/hksong/.virtualenvs/gradio_theme/lib/python3.8/site-packages/gradio/themes/__init__.py", line 14, in builder
    from gradio.themes.builder import demo
  File "/home/hksong/.virtualenvs/gradio_theme/lib/python3.8/site-packages/gradio/themes/builder.py", line 19, in <module>
    docs_theme_core = gr.documentation.document_fn(gr.themes.Base.__init__, gr.themes.Base)[
AttributeError: module 'gradio' has no attribute 'documentation'
```

### System Info

```shell
3.25.0 (or later)
```

### Severity

annoying

**Comment by abidlabs** [comment]
Ah you’re right, thanks @deepkyu! Would you like to make a PR to fix this?

**Comment by deepkyu** [comment]
Thank you for response @abidlabs 
It's always a great honor for me 👍🏻

**Comment by abidlabs** [comment]
Working for me -- what error are you getting @bent-verbiage?

**Comment by abidlabs** [comment]
Working on 3.28 on Colab: https://colab.research.google.com/drive/1nLWrqwcQB1WAz9o0F_gxsC3ZDqhmrbiC?usp=sharing

**Comment by abidlabs** [comment]
Hmm that looks like old code. Can you check the version of Gradio you are running?

**Comment by deepkyu** [comment]
@bent-verbiage I also checked it works with `3.28.0`.

`pip show gradio | grep Version` should show the version either `3.28.0`, `3.24.0`, or `3.24.1`.

```bash
# pip install gradio==3.28.0
pip install --upgrade gradio
```

should solve the error.
