### ISSUE TITLE
`gr.Tab()` no longer working?

### ISSUE THREAD

**Issue by oconnoob** [gradio-app/gradio#2146]
### Describe the bug

The [quickstart](https://gradio.app/controlling_layout/#tabs) has an example with `gr.Tab()` that appears to perhaps be deprecated now? When I try to use `gr.Tab()` I get `AttributeError: module 'gradio' has no attribute 'Tab'. Did you mean: 'Tabs'?`. Replaced `Tab` with `Tabs` does not appear to give the intended result.

Is there still a tab feature with Gradio 3.1.7?

Thanks!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

import numpy as np
import gradio as gr

def flip_text(x):
    return x[::-1]

def flip_image(x):
    return np.fliplr(x)

with gr.Blocks() as demo:
    gr.Markdown("Flip text or image files using this demo.")
    with gr.Tab("Flip Text"):
        text_input = gr.Textbox()
        text_output = gr.Textbox()
        text_button = gr.Button("Flip")
    with gr.Tab("Flip Image"):
        with gr.Row():
            image_input = gr.Image()
            image_output = gr.Image()
        image_button = gr.Button("Flip")

    text_button.click(flip_text, inputs=text_input, outputs=text_output)
    image_button.click(flip_image, inputs=image_input, outputs=image_output)

demo.launch()

### Logs

```shell
Traceback (most recent call last):
  File "C:\<PATH>\testing.py", line 12, in <module>
    with gr.Tab("Flip Text"):
AttributeError: module 'gradio' has no attribute 'Tab'. Did you mean: 'Tabs'?

Process finished with exit code 1
```

### System Info

```shell
Win11, Gradio 3.1.7, Edge/Chrome
```

### Severity

serious, but I can work around it

**Comment by abidlabs** [comment]
Our docs are out of sync with the latest version released on pypi, but this will be fixed very shortly when we release `gradio==3.2`!

**Comment by abidlabs** [comment]
Should work with `gradio--3.2`!

**Comment by oconnoob** [comment]
Thanks! Upgraded to 3.2 and it's working fine
