### ISSUE TITLE
Chatbot "type" argument

### ISSUE THREAD

**Issue by attashe** [gradio-app/gradio#12540]
### Describe the bug

Example from documentation doesn't work in gradio version `==6.1.0`:

https://www.gradio.app/docs/gradio/chatbot

Code:

```python
import gradio as gr

history = [
    gr.ChatMessage(role="assistant", content="How can I help you?"),
    gr.ChatMessage(role="user", content="Can you make me a plot of quarterly sales?"),
    gr.ChatMessage(role="assistant", content="I am happy to provide you that report and plot.")
]

with gr.Blocks() as demo:
    gr.Chatbot(history, type="messages")

demo.launch()
```

Return next error:

```
Traceback (most recent call last):
  File "/workspace/example.py", line 10, in <module>
    gr.Chatbot(history, type="messages")
  File "/usr/local/lib/python3.12/dist-packages/gradio/component_meta.py", line 194, in wrapper
    return fn(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: Chatbot.__init__() got an unexpected keyword argument 'type'

### Have you searched existing issues?  🔎

- [x] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr

history = [
    gr.ChatMessage(role="assistant", content="How can I help you?"),
    gr.ChatMessage(role="user", content="Can you make me a plot of quarterly sales?"),
    gr.ChatMessage(role="assistant", content="I am happy to provide you that report and plot.")
]

with gr.Blocks() as demo:
    gr.Chatbot(history, type="messages")

demo.launch()
```

### Logs

```shell

```

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Linux
gradio version: 6.1.0
gradio_client version: 2.0.1

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 24.1.0
anyio: 4.11.0
audioop-lts is not installed.
brotli: 1.2.0
fastapi: 0.124.0
ffmpy: 1.0.0
gradio-client: 2.0.1
groovy: 0.1.2
httpx: 0.28.1
huggingface-hub: 1.2.1
jinja2: 3.1.6
markupsafe: 3.0.3
numpy: 2.1.2
orjson: 3.11.5
packaging: 25.0
pandas: 2.3.3
pillow: 11.0.0
pydantic: 2.12.4
pydub: 0.25.1
python-multipart: 0.0.20
pyyaml: 6.0.3
safehttpx: 0.1.7
semantic-version: 2.10.0
starlette: 0.50.0
tomlkit: 0.13.3
typer: 0.20.0
typing-extensions: 4.15.0
uvicorn: 0.38.0
mcp is not installed.
pydantic: 2.12.4
authlib is not installed.
itsdangerous is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.6.1
httpx: 0.28.1
huggingface-hub: 1.2.1
packaging: 25.0
typing-extensions: 4.15.0
```

### Severity

I can work around it

**Comment by abidlabs** [comment]
This has been fixed in https://github.com/gradio-app/gradio/pull/12538, and the docs will update when we release the next version of gradio, thanks!
